#!/system/bin/sh

REPO="Scheldest/DEX-ENC-Validation"
VAR_NAME="DB_ENDPOINT"

echo "[*] Mencoba mengambil URL dari GitHub..."
GH_URL=$(gh variable get $VAR_NAME --repo $REPO 2>/dev/null)

if [[ "$GH_URL" == *".trycloudflare.com"* ]]; then
    CLOUDFLARE_URL=$GH_URL
    echo "[+] URL ditemukan otomatis: $CLOUDFLARE_URL"
else
    echo "[-] Gagal mengambil otomatis."
    echo -n "Masukkan URL Cloudflare secara manual: "
    read CLOUDFLARE_URL
fi

CLOUDFLARE_URL=$(echo "$CLOUDFLARE_URL" | tr -cd '[:alnum:].://-')

if [ -z "$CLOUDFLARE_URL" ]; then
    echo "[-] Error: URL tidak boleh kosong!"
    exit 1
fi

echo "[*] URL Bersih: $CLOUDFLARE_URL"

KALIROOT="/data/local/nhsystem/kali-arm64"
TMPDIR="$KALIROOT/tmp"
XDG_RUNTIME_DIR="$KALIROOT/tmp/XDG"

pulseaudio --start --exit-idle-time=-1 --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --load="module-sles-sink" --load="module-null-sink sink_name=MySink"

sleep 1

termux-x11 :0 -ac &

am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1

sleep 1

PROFILE="/home/kali/.local/share/remmina/group_rdp_windows-11_localhost-3389.remmina"

su -c "busybox chroot $KALIROOT /bin/su - kali -c \" \
    export PULSE_SERVER=127.0.0.1 && \
    export DISPLAY=:0 && \
    export TMPDIR=/tmp && \
    export XDG_RUNTIME_DIR=/tmp/XDG && \
    export XKB_CONFIG_ROOT=/usr/share/X11/xkb && \
    (cloudflared access tcp --hostname $CLOUDFLARE_URL --listener 127.0.0.1:3389 &) && \
    sleep 3 && \
    dbus-run-session -- remmina -c '$PROFILE' \
    pkill -9 cloudflare\""

gh run list --repo $REPO --limit 50 --json databaseId -q '.[].databaseId' | xargs -I{} gh run delete {} --repo $REPO 2>/dev/null

echo "[+] Menutup tunnel
pkill -9 app_process